
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class CriarConta extends javax.swing.JFrame {

    /**
     * Creates new form CriarConta
     */
    public CriarConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Criar Conta");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("SIAPE:");

        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                    .addComponent(jTextField2))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    setVisible(false);
    new TelaLogin().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String email = "";  
    String idPessoa  = "";
    String username = "";
            
            Statement stmt = null;
            try {
                SingletonSessao.Connect("checkmat","root","");
                stmt = SingletonSessao.getConn().createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(CriarConta.class.getName()).log(Level.SEVERE, null, ex);
            }
            ResultSet rs = null;
            try {
                jTextField2.setText(jTextField2.getText().replace(".","").replace("-",""));
                rs = stmt.executeQuery("SELECT email,possuiConta,id from pessoa WHERE nome='" + jTextField1.getText() + "' AND cpf='" + jTextField2.getText() + "' AND siape='"+jTextField3.getText()+"'");
                boolean flag = rs.next();
                if(flag==true)
                {
                    int possuiConta = Integer.parseInt(rs.getString("possuiConta"));
                    if(possuiConta==1)
                    {
                    JOptionPane.showMessageDialog(rootPane,"Esta conta já foi ativada...\nCaso esta seja a sua conta, tente recuperar a conta na Tela de Login.\n\nEsta atividade será notificada ao administrador...", "Criar Conta - Cadastrar email", JOptionPane.ERROR_MESSAGE);
                    }
                    else
                    {
                    email = rs.getString("email");
                    idPessoa = rs.getString("id");
                        if(email!=null)
                        {
                        Object[] options = {"Sim, este é o meu email",
                                            "Não, este não é meu email"};
                        int n = JOptionPane.showOptionDialog(rootPane,
                            "Talvez este email possa ser seu...\n"
                            +email 
                            +"\n\nGostaria de utilizá-lo no seu cadastro?",
                            "Criar Conta - Cadastrar email",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.QUESTION_MESSAGE,
                            null,
                            options,
                            options[1]);   
                            if(n!=0)
                            {
                            email = JOptionPane.showInputDialog(rootPane,"Informe seu email: ", "Criar Conta - Cadastrar email", JOptionPane.INFORMATION_MESSAGE);
                            }
                        }
                        else
                        {
                        email = JOptionPane.showInputDialog(rootPane,"Informe seu email: ", "Criar Conta - Cadastrar email", JOptionPane.INFORMATION_MESSAGE);
                        }
                    }
                    username = JOptionPane.showInputDialog(rootPane,"Sua conta está quase pronta...\nEscolha um nome de usuário que você irá utilizar:", "Criar Conta - Escoher nome de usuário", JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(rootPane,"Conta criada com sucesso.\nA senha da sua conta foi enviada ao seu email.\nVocê poderá altera-la uma vez que efetuar o login.", "Criar Conta - Cadastrar email", JOptionPane.PLAIN_MESSAGE);
                    stmt.execute("UPDATE pessoa SET possuiConta='1', email='"+email+"', siape='"+jTextField3.getText()+"' WHERE CPF='"+jTextField2.getText()+"'");
                    String senha = GeraSenha();
                    stmt.execute("INSERT INTO `checkmat`.`user` (`usuario`, `senha`, `FK_idPessoa`, `isLoggedIn`) VALUES ('" + username +"', '"+senha+"', '" + idPessoa + "', '0');");
                    System.out.println(senha);
                    CarteiroEmail.EnviarEmail("luisviniciuscostasilva@gmail.com","luisviniciuscostasilva@gmail.com","Checkmat - Obrigado por criar conta",
                    
                            "Olá " + jTextField1.getText() + ", \n"
                                    + "Muito Obrigado por criar uma conta. Os dados para login na sua conta são:\n\n"
                                    + "Nome de usuário: " + username + "\n"
                                    + "Senha: " + senha + "\n\n\n"
                                    + "Sugerimos que troque sua senha assim que você entrar na sua conta.\n\n"
                                    + "O Checkmat está em fase Beta, então algumas complicações podem ser encontradas durante seu uso.\n\n"
                                    + "Este sistema foi desenvolvido na disciplina de Fábrica de Software no curso de Bacharelado em Ciência da"
                                    + " Computação da UFG - Regional Catalão\n\n"
                                    + "Caso você precise reportar algum problema ou dar sua opinião sobre esse sistema, contate os desenvolvedores através dos endereços de email abaixo:\n\n"
                                    + "[Prof. de Fábrica de Software] Renato França: renatofrn@gmail.com\n"
                                    + "[Desenvolvedor] Hallefy Ferreira: hallefy.fc@gmail.com\n"
                                    + "[Desenvolvedor] Erly Araújo: erlyalf@gmail.com@gmail.com\n"
                                    + "[Desenvolvedor] Luis Vinicius Costa Silva: luisviniciuscostasilva@gmail.com\n\n"
                                    + "Saudações,\n"
                                    + "Equipe Desenvolvedora.");                
                    this.setVisible(false);
                    new TelaLogin().setVisible(true);
                }
                else
                {
                JOptionPane.showMessageDialog(rootPane,"Dados Incorretos!\nO acesso ao sistema é exclusivo aos servidores da UFG","Criar Conta", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(CriarConta.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private String GeraSenha () {
    char[] chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".toCharArray();
    StringBuilder sb = new StringBuilder();
    Random random = new Random();
    for (int i=0;i<8;i++) {
    char c = chars[random.nextInt(chars.length)];
    sb.append(c);
    }
    return sb.toString();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
